name: Import and Merge Sunfish Kernel

on:
  workflow_dispatch:

jobs:
  merge-sunfish-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Sunfish kernel (full history, correct branch)
        run: |
          git clone https://android.googlesource.com/kernel/msm sunfish-kernel
          cd sunfish-kernel
          git fetch origin android-msm-sunfish-4.14-android13-qpr3
          git checkout android-msm-sunfish-4.14-android13-qpr3
          echo "KERNEL_LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          cd ..

      - name: Add sunfish-kernel as remote and fetch
        run: |
          git remote add sunfish-kernel ./sunfish-kernel
          git fetch sunfish-kernel

      - name: Create new branch for merge
        run: |
          git checkout -b sunfish_merged

      - name: Merge Sunfish kernel (allow unrelated histories)
        run: |
          git merge sunfish-kernel/android-msm-sunfish-4.14-android13-qpr3 --allow-unrelated-histories -m "Merge Sunfish kernel history into repo"

      - name: Push merged branch to your repo
        run: |
          git push "https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git" sunfish_merged:sunfish_merged

      - name: Create branch at specific Sunfish commit (sunfishkernel2023)
        run: |
          git fetch ./sunfish-kernel 6ff6ddc33f7db8b0e858c38b082dbc1fcc351071
          git checkout -b sunfishkernel2023 6ff6ddc33f7db8b0e858c38b082dbc1fcc351071

      - name: Push sunfishkernel2023 branch to your repo
        run: |
          git push "https://${{ github.actor }}:${{ secrets.PAT }}@github.com/${{ github.repository }}.git" sunfishkernel2023:sunfishkernel2023

      - name: Show remotes for verification
        run: git remote -v